name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - name: Run a multi-line script
      run: black /Prototype ,
        echo Successful formating
        
      
